import { Metadata } from "next";
import AdminHeader from "./_components/AdminHeader";


export const metadata: Metadata = {
  title: "Quote System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div>
        <AdminHeader />
        {children}
      </div>
  );
}